# Generated by Django 5.0.6 on 2024-05-20 02:09

import Bakery.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('idFecha', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dia', models.IntegerField(validators=[Bakery.models.validate_day])),
                ('mes', models.IntegerField(validators=[Bakery.models.validate_month])),
                ('anio', models.IntegerField()),
                ('hInicio', models.TimeField()),
                ('hFinal', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idp', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=100)),
                ('nomProducto', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('Descrip', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('idr', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idU', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEntrega',
            fields=[
                ('codigoDireccion', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('estadoPedido', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristicasPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdPedido', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('idp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bakery.producto')),
            ],
        ),
        migrations.CreateModel(
            name='MedioTransp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=100)),
                ('fechaVenci', models.DateField()),
                ('licencia', models.CharField(max_length=100)),
                ('idr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.repartidor')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('codigoEntrega', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.direccionentrega')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.cliente')),
                ('Fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.fecha')),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.pedido')),
                ('idr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.repartidor')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasDisp', models.CharField(max_length=150)),
                ('horasDisp', models.CharField(max_length=150)),
                ('idr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.repartidor')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('Numero', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='idC',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bakery.usuario'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAdmin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bakery.usuario')),
            ],
        ),
    ]
