# Generated by Django 5.0.6 on 2024-06-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoproducto',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
