# Generated by Django 5.0.6 on 2024-06-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
    ]
