# Generated by Django 5.0.6 on 2024-06-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos_por_dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(unique=True)),
                ('cantidadp', models.IntegerField(default=0)),
            ],
        ),
    ]
