# Generated by Django 5.0.6 on 2024-05-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idp',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
