# Generated by Django 5.0.6 on 2024-05-27 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idc',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='itemcarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('idcarrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.carrito')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='caracteristicaspedido',
        ),
    ]
