# Generated by Django 5.0.6 on 2024-06-05 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto_mas_vendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadt', models.PositiveIntegerField(default=0)),
                ('productotendencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bakery.producto')),
            ],
        ),
    ]
