# Generated by Django 5.0.6 on 2024-05-31 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carritoproducto',
            unique_together=set(),
        ),
    ]
