# Generated by Django 5.0.6 on 2024-05-22 04:13

import Bakery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0002_alter_producto_idp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='codigoEntrega',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idPedido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(validators=[Bakery.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='idr',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idU',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
