# Generated by Django 5.0.6 on 2024-05-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0002_cliente_admin_alter_cliente_idc_carrito_itemcarrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descrip',
            field=models.TextField(default=''),
        ),
    ]
