# Generated by Django 5.0.6 on 2024-06-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0002_pedidos_por_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidosperiodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('cantidadp', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('fechainicio', 'fechafin')},
            },
        ),
    ]
