# Generated by Django 5.0.6 on 2024-05-31 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0002_alter_carritoproducto_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carritoproducto',
            unique_together={('carrito', 'producto')},
        ),
    ]
