# Generated by Django 5.0.6 on 2024-05-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0003_producto_imagen_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccionentrega',
            name='codigodireccion',
        ),
        migrations.AlterField(
            model_name='direccionentrega',
            name='direccion',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
